pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=paoloboni
      - title~=^Update\s.*
      - "status-success=test (openjdk@1.11, 2.12.16)"
      - "status-success=test (openjdk@1.11, 2.13.8)"
      - "status-success=test (openjdk@1.11, 3.2.0)"
      - "status-success=test (openjdk@1.17, 2.12.16)"
      - "status-success=test (openjdk@1.17, 2.13.8)"
      - "status-success=test (openjdk@1.17, 3.2.0)"
      - "status-success=e2e (2.13.8)"
      - "status-success=e2e (3.2.0)"
    actions:
      merge:
        method: squash
