addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("com.github.sbt"    % "sbt-pgp"      % "2.1.2")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.7")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.6.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
