addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"      % "2.2.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.9.18")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.9.0")
addSbtPlugin("com.github.sbt"            % "sbt-release"  % "1.1.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"     % "1.4.1")
addSbtPlugin("com.github.sbt"            % "sbt-ghpages"  % "0.7.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.2")
